version: '3'
services:
  service1:
    build: 
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  service2:
    build: 
      context: ./items-management
      dockerfile: Dockerfile
    ports:
      - "8081:8081"

  service3:
    build: 
      context: ./cart
      dockerfile: Dockerfile
    ports:
      - "8082:8082"

  service4:
    build: 
      context: ./payment
      dockerfile: Dockerfile
    ports:
      - "80:80"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
