version: '3'
services:
  auth:
    build: 
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - mynetwork

  items:
    build: 
      context: ./items-management
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    networks:
      - mynetwork

  cart:
    build: 
      context: ./cart
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - mongo
    networks:
      - mynetwork

  payment:
    build: 
      context: ./payment
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - cart
    networks:
      - mynetwork

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mynetwork

networks:
  mynetwork:
