logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG

jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub

server:
  port: 8080
  servlet:
    session:
      timeout: 30m

spring:
  main:
    allow-circular-references: true
  application:
    name: auth-service
  data:
    mongodb:
      uri: mongodb://mongo:27017/fiap
